version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - $DB_PORT:5432

volumes:
  db:
