version: '3'

tasks:
  default:
    desc: 'Install all required dependencies to use the project'
    cmds:
      - cmd: go install github.com/pressly/goose/v3/cmd/goose@latest
      - cmd: brew install goose
        ignore_error: true
      - cmd: go mod tidy
      - cmd: task migrate:up
